In [7]:
import cv2
import numpy as np

In [4]:
# Tải ảnh đầu vào
img = cv2.imread('./Images/face.png')

# Hiển thị ảnh gốc
cv2.imshow('Ảnh gốc', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
net = cv2.dnn.readNetFromCaffe(
    './models/deploy.prototxt.txt',
    './models/res10_300x300_ssd_iter_140000.caffemodel'
)
blob = cv2.dnn.blobFromImage(img, 1.0, (300, 300), (104, 177, 123), swapRB=False)

# Đặt dữ liệu đầu vào cho mạng
net.setInput(blob)

# Chạy mạng để phát hiện khuôn mặt
faces = net.forward()

# Lấy kích thước của ảnh đầu vào
h = img.shape[0]
w = img.shape[1]

# In thông tin
print(faces.shape)
print(faces[0, 0, 0, ])

# Duyệt từng khuôn mặt đã được phát hiện
for i in range(0, faces.shape[2]):
    confidence = faces[0,0,i,2]
    # Kiểm tra nếu mặt có độ tin cậy là 0.5
    if confidence>0.5:
        # Trích xuất tọa độ
        print(faces[0, 0, i, 3:7])
        startx = int(faces[0, 0, i, 3]*w)
        starty = int(faces[0, 0, i, 4]*h)
        endx = int(faces[0, 0, i, 5]*w)
        endy = int(faces[0, 0, i, 6]*h)
        print(startx, starty, endx, endy)
        
        # Vẽ hình chữ nhật xung quanh khuôn mặt đã phát hiện
        cv2.rectangle(img, (startx, starty), (endx, endy), (0, 255, 0),)
        
        # Hiển thị độ tin cậy
        text = 'Face: {:.2f}%'.format(confidence*100);
        cv2.putText(img, text, (startx, starty-10), cv2.FONT_HERSHEY_PLAIN, 1, (255,255,255),)

# Hiển thị ảnh gốc
cv2.imshow('Kết quả', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(1, 1, 200, 7)
[0.         1.         0.9999964  0.08431795 0.03673185 0.2728949
 0.21403477]
[0.08431795 0.03673185 0.2728949  0.21403477]
63 36 204 213
[0.40015897 0.02710085 0.579692   0.22908509]
300 27 434 228
[0.75269264 0.79041857 0.94096524 0.9887622 ]
564 789 705 987
[0.75594354 0.02493584 0.9462501  0.23191467]
566 24 709 231
[0.08840561 0.79843307 0.25066006 0.984727  ]
66 797 187 983
[0.7299378  0.27312317 0.9186108  0.4858645 ]
547 272 688 485
[0.74944067 0.542148   0.93323517 0.7356492 ]
562 541 699 734
[0.42464206 0.29030454 0.5999834  0.4685061 ]
318 290 449 468
[0.07715236 0.29420447 0.24884781 0.4731152 ]
57 293 186 472
[0.38338488 0.79235077 0.56548774 0.9834354 ]
287 791 424 982
[0.43101722 0.534801   0.6274341  0.73482895]
323 534 470 734
[0.07509262 0.5484283  0.24415904 0.722643  ]
56 547 183 721
